### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Loltolo-Lesapiti** [Loltolo-Lesapiti/recipe-app#13]
https://github.com/users/Loltolo-Lesapiti/projects/2/views/1
We are a team of two.
1. [Nabeel Akbar](https://github.com/studiosnabeel)
2. [Loltolo Lesapiti](https://github.com/Loltolo-Lesapiti )

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add a description for all tasks as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). The description should include what you are planning to do in each task.
![image](https://user-images.githubusercontent.com/24703171/226325219-9c26e0dc-5a47-4844-a3d8-46cb8302db38.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
